### ISSUE TITLE
compilation on Ubuntu 16.04

### ISSUE THREAD

**Issue by d-chambers** [dttrugman/GrowClust#2]
I recently cloned GrowClust and compiled following the instructions in the PDF included with the repo. Everything appeared to work fine. However, when I tried running the example I got the following error:
```
error while loading shared libraries: libgfortran.so.4: cannot open shared object file: No such file or directory
```
I found [this SO post](https://stackoverflow.com/questions/46516394/how-to-install-libgfortran-so-4-on-ubuntu-16-06) which indicates it is because gfortran-4 is needed, which is part of gcc-7. The gcc version for Ubuntu 16.04 is 4, so it is rather outdated. According to [this page](https://unix.stackexchange.com/questions/371737/install-gcc-7-on-ubuntu) a PPA from some "jonathonf" has to be added or the OS needs to be updated to Ubuntu 18.04 to install gcc-7. I ended up adding the PPA and installing gfortran-4. I then had to change the makefile to use gfortran-4. The example seems to run fine now.

I don't know enough about fortran to know if the code can be adapted to be compatible with both gfortran-3 and gfortran-4. If not, a small blurb about this in the documentation may be useful to new users, as Ubuntu 16.04 is a common operating system.

**Comment by d-chambers** [comment]
Ok, turns out the gcc installed with the python package Anaconda is version 4.8.5 on my machine. When I remove Anaconda from Path so that the gfortran refers to the system gcc (version 5.4.0) everything seems to work fine. Dumb mistake on my part.

**Comment by dttrugman** [comment]
Oh, interesting. Thanks for testing this out. I've run GrowClust on Linux,
but not Ubuntu so I wouldn't have encountered this problem. Compiler issues
are not my forte, but it's good for me to be aware of these types of
problems.

Thanks for your interest in the code.

Daniel
