### ISSUE TITLE
bootstrap distribution column specs dont match those described in manual

### ISSUE THREAD

**Issue by d-chambers** [dttrugman/GrowClust#3]
The column specs defined in the manual for the bootstrap distribution appear to be inconsistent with those output after running the example case provided with GrowClust.

For example, the second line from out.growclust_boot in the example directory reads:
```
       1    956586  39.66202 -119.68910   7.756       1     710 718.40     712     721  39.66224 -119.68938   7.712   0.019   0.308   0.004   0.137   0.545   0.007
```
but the manual (page 18) indicates the following for the first few columns:

```
The event header lines (nq total within the file) contain the following fields:
• qID, eID: event serial ID number (range: 1 to nq), event ID (non-serial, e.g. a CUSPID or EVID)
• yr, mon, day, hr, min, sec: relocated event origin time
• latR, lonR, depR: relocated event latitude, longitude and depth (decimal degrees and km)
```

The main discrepancy is the lack of time fields.

**Comment by dttrugman** [comment]
Good catch, now fixed.
